import { StandingRow } from '../domain/club.models';

// Generated by npm run import:calendar. This checked-in snapshot is the offline fallback.
export const STANDINGS_UPDATED_AT = "2026-09-29";

export const INITIAL_STANDINGS: StandingRow[] = [
  {
    "teamId": "152_1_forestois_sc",
    "name": "FORESTOIS SC",
    "played": 5,
    "wins": 5,
    "draws": 0,
    "losses": 0,
    "goalsFor": 15,
    "goalsAgainst": 2,
    "goalDifference": 13,
    "points": 15
  },
  {
    "teamId": "686_1_fc_phoenix",
    "name": "FC PHOENIX",
    "played": 5,
    "wins": 3,
    "draws": 1,
    "losses": 1,
    "goalsFor": 15,
    "goalsAgainst": 4,
    "goalDifference": 11,
    "points": 10
  },
  {
    "teamId": "662_1_l_ekip",
    "name": "L'EKIP",
    "played": 5,
    "wins": 3,
    "draws": 1,
    "losses": 1,
    "goalsFor": 13,
    "goalsAgainst": 6,
    "goalDifference": 7,
    "points": 10
  },
  {
    "teamId": "687_1_interim_milan",
    "name": "INTERIM MILAN",
    "played": 5,
    "wins": 3,
    "draws": 1,
    "losses": 1,
    "goalsFor": 9,
    "goalsAgainst": 9,
    "goalDifference": 0,
    "points": 10
  },
  {
    "teamId": "100_1_faubourg_brainoise",
    "name": "FAUBOURG-BRAINOISE",
    "played": 5,
    "wins": 3,
    "draws": 0,
    "losses": 2,
    "goalsFor": 18,
    "goalsAgainst": 8,
    "goalDifference": 10,
    "points": 9
  },
  {
    "teamId": "39_4_brussels_ltc",
    "name": "BRUSSELS LTC (Eq. 4)",
    "played": 5,
    "wins": 3,
    "draws": 0,
    "losses": 2,
    "goalsFor": 12,
    "goalsAgainst": 12,
    "goalDifference": 0,
    "points": 9
  },
  {
    "teamId": "653_1_winchester_f_c",
    "name": "WINCHESTER F.C.",
    "played": 5,
    "wins": 2,
    "draws": 1,
    "losses": 2,
    "goalsFor": 11,
    "goalsAgainst": 13,
    "goalDifference": -2,
    "points": 7
  },
  {
    "teamId": "626_2_celtic_roosters",
    "name": "CELTIC ROOSTERS (Eq. 2)",
    "played": 5,
    "wins": 2,
    "draws": 0,
    "losses": 3,
    "goalsFor": 7,
    "goalsAgainst": 12,
    "goalDifference": -5,
    "points": 6
  },
  {
    "teamId": "627_1_macapsules_les",
    "name": "MACAPSULES (LES)",
    "played": 5,
    "wins": 1,
    "draws": 3,
    "losses": 1,
    "goalsFor": 8,
    "goalsAgainst": 5,
    "goalDifference": 3,
    "points": 6
  },
  {
    "teamId": "16_1_oni_rfc",
    "name": "ONI RFC",
    "played": 5,
    "wins": 1,
    "draws": 2,
    "losses": 2,
    "goalsFor": 12,
    "goalsAgainst": 11,
    "goalDifference": 1,
    "points": 5
  },
  {
    "teamId": "641_1_sneaky_baboons",
    "name": "SNEAKY BABOONS",
    "played": 5,
    "wins": 1,
    "draws": 1,
    "losses": 3,
    "goalsFor": 5,
    "goalsAgainst": 9,
    "goalDifference": -4,
    "points": 4
  },
  {
    "teamId": "593_1_deaf_brussels_fc",
    "name": "DEAF BRUSSELS FC",
    "played": 5,
    "wins": 1,
    "draws": 1,
    "losses": 3,
    "goalsFor": 7,
    "goalsAgainst": 16,
    "goalDifference": -9,
    "points": 4
  },
  {
    "teamId": "665_1_fraudes_les",
    "name": "FRAUDES (LES)",
    "played": 5,
    "wins": 0,
    "draws": 2,
    "losses": 3,
    "goalsFor": 2,
    "goalsAgainst": 14,
    "goalDifference": -12,
    "points": 2
  },
  {
    "teamId": "7_1_elan_evere_rac",
    "name": "ELAN EVERE RAC",
    "played": 5,
    "wins": 0,
    "draws": 1,
    "losses": 4,
    "goalsFor": 5,
    "goalsAgainst": 18,
    "goalDifference": -13,
    "points": 1
  }
];
